FROM node:18-alpine

WORKDIR /app

# Install dependencies
COPY package*.json ./
RUN npm install --legacy-peer-deps

# Copy project files
COPY . .

# Expose port and start development server
EXPOSE 3000
CMD ["npm", "run", "dev"]